CREATE TABLE IF NOT EXISTS user (
user_id VARCHAR(20) PRIMARY KEY, 
pass  VARCHAR(20) NOT NULL,
first_name VARCHAR(40) NOT NULL, 
last_name VARCHAR(20) NOT NULL, 
role VARCHAR(20) NOT NULL,
branch VARCHAR(20) NOT NULL,
phone_num VARCHAR(20) NOT NULL,
email VARCHAR(40) NOT NULL,
reg_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP );

CREATE TABLE IF NOT EXISTS subject (
subject_code VARCHAR(20) PRIMARY KEY,
subject_name VARCHAR(20) UNIQUE NOT NULL,
semester INT NOT NULL,
theory INT NOT NULL,
practical INT NOT NULL);

CREATE TABLE IF NOT EXISTS marks (
role VARCHAR(20) NOT NULL,
user_id VARCHAR(20) NOT NULL,
subject_code VARCHAR(20) NOT NULL,
marks_theory INT NOT NULL,
marks_practical INT NOT NULL);

