CREATE TABLE IF NOT EXISTS students (
roll_num VARCHAR(20) PRIMARY KEY NOT NULL, 
first_name VARCHAR(40) NOT NULL, 
last_name VARCHAR(20) NOT NULL, 
branch VARCHAR(20) NOT NULL,
phone_num VARCHAR(20) NOT NULL,
email VARCHAR(40) NOT NULL, 
reg_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP );


CREATE TABLE IF NOT EXISTS teacher (
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
uname VARCHAR(20) NOT NULL,
pass VARCHAR(20) NOT NULL,
teacher_name VARCHAR(20) NOT NULL,
branch VARCHAR(20) NOT NULL,
subject VARCHAR(20) NOT NULL);

-- For Branch Details : ECE

CREATE TABLE IF NOT EXISTS ece(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
subject_name VARCHAR(20) NOT NULL,
subject_code VARCHAR(20) NOT NULL,
theory VARCHAR(20) NOT NULL,
practical VARCHAR(20) NOT NULL);

-- For Branch Details : CSE

CREATE TABLE IF NOT EXISTS cse(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
subject_name VARCHAR(20) NOT NULL,
subject_code VARCHAR(20) NOT NULL,
theory VARCHAR(20) NOT NULL,
practical VARCHAR(20) NOT NULL);

-- For Branch Details : IT

CREATE TABLE IF NOT EXISTS it(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
subject_name VARCHAR(20) NOT NULL,
subject_code VARCHAR(20) NOT NULL,
theory VARCHAR(20) NOT NULL,
practical VARCHAR(20) NOT NULL);


-- For Branch Details : EE

CREATE TABLE IF NOT EXISTS ee(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
subject_name VARCHAR(20) NOT NULL,
subject_code VARCHAR(20) NOT NULL,
theory VARCHAR(20) NOT NULL,
practical VARCHAR(20) NOT NULL);

-- For Branch Details : ME

CREATE TABLE IF NOT EXISTS me(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
subject_name VARCHAR(20) NOT NULL,
subject_code VARCHAR(20) NOT NULL,
theory VARCHAR(20) NOT NULL,
practical VARCHAR(20) NOT NULL);

